### ISSUE TITLE
Add Workflows

### ISSUE THREAD

**Issue by frank113** [vincentarelbundock/pycountrycode#1]
# Summary

Implement `.github/worfklows` to do the following:

+ Lint with our linter of choice (`pylint`, `black`, etc)
+ Run unit tests 
+ Confirm build and installation on windows, mac and linux

Implementing basic checks early in the development process and provide needed velocity as this port matures. 

# Considerations

+ The choice of linter: `pylint` and `black` are good starting points
+ How to orchestrate workflows

# Other

I am a long time user of `countrycode` since my time in graduate school and am very excited to see a Python port!

**Comment by vincentarelbundock** [comment]
That's great to hear!

I love the suggestion. However, I'm super busy with "real work" these days, so I can't really afford the time to figure this stuff out right now. We can leave the issue open and I might come back to it eventually. Alternatively, I'd be thrilled to merge a pull request if you or someone else feels like helping.

Cheers!
